"""Phase 2 finalization, P2-16: LUMEN's opinions are exogenous input.

Found during the final Phase 2 audit, and confirmed by reproduction before
anything was changed.

LUMEN reads the information environment through an intelligence provider --
Claude, by configuration -- and publishes an ``AGENT_OPINION`` that carries
consensus weight 0.5. Nothing in a recording lets replay recompute what a
language model said, and calling the model again would produce a different
answer (and cost money, and need a network, in the middle of what is supposed
to be a hermetic reproduction).

Before this fix, replay did neither: LUMEN's loop is driven only by the live
``apps.orchestrator.__main__`` process, so it never ran during replay, and
``AGENT_OPINION`` is not in ``MARKET_INPUT_TYPES``, so the recorded opinion
was never replayed either. A session in which LUMEN moved consensus therefore
replayed WITHOUT that input -- and reported verified fidelity while doing it.

The contract now:

* Externally-produced opinions (``EXTERNAL_INTELLIGENCE_SOURCES``) are
  replayed as recorded inputs, exactly like a recorded book snapshot.
* Opinions derived deterministically from market data -- TIDAL, NORO, ZEPHR --
  are still RECOMPUTED. Replaying those would defeat the point of replay: a
  change to an agent would stop showing up as a different answer.
* Dropping external intelligence is possible, and is reported as
  ``UNVERIFIED_EXTERNAL_INTELLIGENCE`` rather than presented as exact.
"""

from __future__ import annotations

import pytest

from apps.orchestrator.wiring import build_platform
from core.bus import InMemoryEventBus
from core.clock import ManualClock
from core.config import simulated_venues
from core.events import Event, EventType
from core.models.agent import AgentOpinion
from core.models.common import AgentId
from replay.engine import (
    EXTERNAL_INTELLIGENCE_SOURCES,
    UNVERIFIED_EXTERNAL_INTELLIGENCE,
    FidelityDimension,
    ReplaySession,
    config_digest,
)
from simulation.market import default_market
from storage import InMemoryEventStore
from tests.conftest import START_MS
from tests.replay.test_replay import fresh_platform, replay_equivalence_summary

TICKS = 60
#: The tick after which the scripted intelligence arrives, mid-session and
#: between ticks -- which is how LUMEN's slow loop actually fires.
OPINION_AT_TICK = 20


def lumen_opinion(ts_ms: int, symbol: str, *, signal: float = -0.9) -> Event:
    opinion = AgentOpinion(
        agent_id=AgentId.LUMEN,
        symbol=symbol,
        created_at=ts_ms,
        signal=signal,
        confidence=0.9,
        expires_at=ts_ms + 600_000,
        reason_codes=["NEGATIVE_INFORMATION_SHOCK"],
        model_version="lumen-0.1",
    )
    return Event(
        type=EventType.AGENT_OPINION,
        ts_ms=ts_ms,
        source="LUMEN",
        schema_name="AgentOpinion",
        payload=opinion.to_json_dict(),
    )


async def record_with_intelligence(settings, *, opinions: bool = True):
    """A real recorded session, optionally carrying a LUMEN opinion.

    The opinion is published onto the bus mid-run rather than generated by a
    provider, which is exactly what a scripted/deterministic provider would
    have produced -- and lets the test pin the replay contract without
    depending on an external service.
    """
    store = InMemoryEventStore()
    platform = fresh_platform(settings, store=store)
    await platform.start(record=True)
    symbol = settings.symbols[0]
    for tick in range(TICKS):
        platform.clock.advance(100)
        await platform.step_market(1)
        await platform.orchestrator.tick()
        if opinions and tick == OPINION_AT_TICK:
            await platform.bus.publish(
                lumen_opinion(platform.clock.now_ms(), symbol)
            )
            await platform.bus.drain()
    await platform.bus.drain()
    session_id = platform.session_id
    await platform.recorder.stop()
    return platform, store, session_id


async def replay_session(settings, store, session_id: str, **kwargs):
    replay_settings = settings.model_copy(update={"venues": simulated_venues()})
    clock = ManualClock(START_MS)
    bus = InMemoryEventBus(raise_on_handler_error=True)
    platform = build_platform(
        replay_settings,
        clock=clock,
        bus=bus,
        store=InMemoryEventStore(),
        market=default_market(start_ms=START_MS),
        raise_on_handler_error=True,
    )
    await platform.start(record=False, feeds=False)
    session = ReplaySession(
        store=store,
        bus=bus,
        clock=clock,
        session_id=session_id,
        current_config_hash=config_digest(replay_settings.model_dump()),
        **kwargs,
    )
    async with session:
        while (event := await session.step()) is not None:
            if event.type is EventType.ORCHESTRATOR_TICK:
                await platform.orchestrator.tick()
    return platform, session


class TestThePolicyIsExplicit:
    def test_lumen_is_the_declared_external_source(self):
        assert frozenset({"LUMEN"}) == EXTERNAL_INTELLIGENCE_SOURCES

    def test_the_deterministic_agents_are_not_external(self):
        """Their opinions are recomputed from market data. Replaying them
        would mean a change to an agent no longer shows up as a different
        answer, which is the entire purpose of replay."""
        for agent in ("TIDAL", "NORO", "ZEPHR", "RUNE"):
            assert agent not in EXTERNAL_INTELLIGENCE_SOURCES

    def test_lumen_carries_real_consensus_weight(self, settings):
        """The reason this matters at all: a dropped LUMEN opinion can change
        what the platform trades."""
        assert settings.consensus.weights.get(AgentId.LUMEN, 0) > 0


class TestRecordedIntelligenceIsReplayed:
    async def test_the_recorded_opinion_reaches_the_replayed_run(self, settings):
        original, store, session_id = await record_with_intelligence(settings)
        symbol = settings.symbols[0]
        assert AgentId.LUMEN in original.state.opinions_for(symbol), (
            "the original run really did receive the opinion"
        )

        replayed, _session = await replay_session(settings, store, session_id)
        try:
            assert AgentId.LUMEN in replayed.state.opinions_for(symbol), (
                "an exogenous input the original run acted on must be "
                "replayed, not silently dropped"
            )
        finally:
            await replayed.stop()
            await original.stop()

    async def test_the_replayed_opinion_is_the_recorded_one(self, settings):
        original, store, session_id = await record_with_intelligence(settings)
        symbol = settings.symbols[0]
        recorded = original.state.opinions_for(symbol)[AgentId.LUMEN].opinion

        replayed, _ = await replay_session(settings, store, session_id)
        try:
            got = replayed.state.opinions_for(symbol)[AgentId.LUMEN].opinion
            assert got.signal == recorded.signal
            assert got.confidence == recorded.confidence
            assert got.created_at == recorded.created_at
            assert got.expires_at == recorded.expires_at
            assert got.reason_codes == recorded.reason_codes
        finally:
            await replayed.stop()
            await original.stop()

    async def test_a_replay_with_intelligence_is_still_exact(self, settings):
        original, store, session_id = await record_with_intelligence(settings)
        replayed, session = await replay_session(settings, store, session_id)
        try:
            assert session.stats.fidelity.verified(
                FidelityDimension.EXTERNAL_INTELLIGENCE
            )
            assert session.stats.is_exact
        finally:
            await replayed.stop()
            await original.stop()

    async def test_original_and_replay_agree_economically(self, settings):
        """The equivalence proof, with an external opinion in the timeline."""
        original, store, session_id = await record_with_intelligence(settings)
        replayed, _ = await replay_session(settings, store, session_id)
        try:
            assert replay_equivalence_summary(original) == (
                replay_equivalence_summary(replayed)
            )
        finally:
            await replayed.stop()
            await original.stop()


class TestDerivedOpinionsAreStillRecomputed:
    async def test_the_agents_own_opinions_are_not_replayed_back(self, settings):
        """TIDAL/NORO/ZEPHR opinions are recorded, and replay must recompute
        them rather than feed them back. If they were replayed, the replayed
        run would hold opinions minted at the ORIGINAL run's identity, and a
        code change to an agent would produce no visible difference."""
        original, store, session_id = await record_with_intelligence(settings)
        derived = [
            e
            async for e in store.read(session_id, types=[EventType.AGENT_OPINION])
            if e.source != "LUMEN"
        ]
        assert derived, "the deterministic agents did publish opinions"

        replayed, session = await replay_session(settings, store, session_id)
        try:
            # Every derived opinion was read past, never applied.
            assert session.stats.events_skipped >= len(derived)
            symbol = settings.symbols[0]
            assert set(replayed.state.opinions_for(symbol)) == {AgentId.LUMEN}, (
                "the ONLY opinion carried in from the recording is the "
                "exogenous one; every other agent's is recomputed"
            )
            # ...and the agents really did run: the replay reached the same
            # decisions from the same market data.
            assert replay_equivalence_summary(replayed) == (
                replay_equivalence_summary(original)
            )
            assert replayed.state.opportunities, (
                "the replayed run computed its own analysis"
            )
        finally:
            await replayed.stop()
            await original.stop()


class TestDroppingIntelligenceIsReportedNotHidden:
    async def test_disabling_it_is_never_called_exact(self, settings):
        original, store, session_id = await record_with_intelligence(settings)
        replayed, session = await replay_session(
            settings, store, session_id, replay_external_intelligence=False
        )
        try:
            fidelity = session.stats.fidelity
            assert fidelity.issues[FidelityDimension.EXTERNAL_INTELLIGENCE] == (
                UNVERIFIED_EXTERNAL_INTELLIGENCE
            )
            assert not fidelity.is_exact
            symbol = settings.symbols[0]
            assert AgentId.LUMEN not in replayed.state.opinions_for(symbol)
        finally:
            await replayed.stop()
            await original.stop()

    async def test_a_session_with_no_intelligence_is_unaffected(self, settings):
        """The default provider is ``null``, so the overwhelming majority of
        sessions carry no external intelligence at all. Those must be exact
        either way -- there is nothing to drop."""
        original, store, session_id = await record_with_intelligence(
            settings, opinions=False
        )
        for flag in (True, False):
            replayed, session = await replay_session(
                settings, store, session_id, replay_external_intelligence=flag
            )
            try:
                assert session.stats.is_exact
            finally:
                await replayed.stop()
        await original.stop()


class TestTheNullProviderStaysDeterministic:
    async def test_a_null_provider_publishes_nothing_to_replay(self, settings):
        """LUMEN's contract when unavailable: no opinion at all, rather than a
        neutral one. Nothing to record, nothing to replay, still exact."""
        from agents.lumen.provider import NullProvider

        original, store, session_id = await record_with_intelligence(
            settings, opinions=False
        )
        try:
            events = [
                e
                async for e in store.read(
                    session_id, types=[EventType.AGENT_OPINION]
                )
            ]
            assert all(e.source != "LUMEN" for e in events)
            assert NullProvider.name == "null"
        finally:
            await original.stop()


@pytest.fixture
def settings(settings):
    """Narrows the shared fixture to the deterministic offline venue set."""
    return settings.model_copy(update={"venues": simulated_venues()})
